---
- hosts: localhost
  vars_files:
  - ../environment.yaml
  - ../global_defaults.yaml
  vars_prompt:
    - name: host_password
      prompt: What is the password of the host?
  tasks:
  - name: Create Key
    openssh_keypair:
      path: '~/.ssh/{{ ggs_keyname }}'
      type: ed25519
  - name: Copy ggs id to host 
    shell:
      cmd: 'sshpass -p {{ host_password }} ssh-copy-id -i ~/.ssh/{{ ggs_keyname }}.pub -o StrictHostKeyChecking=no {{ hostvars.ggs.ansible_user }}@{{ hostvars.ggs.ansible_host }}'
