manifest_folder: ~/geogeek_manifests
gisnamespace: gis
storage_base: '/home/{{ ansible_user }}/geogeek_storage'
storage:
- name: test
  type: local
  path: '{{ storage_base }}/test'
  size: 1M
- name: postgres 
  type: local 
  path: '{{ storage_base }}/postgres'
  size: 5Gi
- name: pgadmin 
  type: local 
  path: '{{ storage_base }}/pgadmin'
  size: 10M