---
- hosts: ggs
  vars_files:
  - ./environment.yaml
  - ./global_defaults.yaml
  tasks:
  - name: Smoke Test
    debug:
      msg: "Hi from {{ ansible_host }}"
  roles:
  - { role: geogeeksuite.kubernetes,
      tags: kube }