---
- hosts: ggs
  vars_files:
  - ./environment.yaml
  - ./global_defaults.yaml
  tasks:
  - name: Smoke Test
    debug:
      msg: "Hi from {{ ansible_host }}"
    tags: ['never','smoketest']
  roles:
  - { role: geogeeksuite.kubernetes,
      tags: kube }
  - { role: geogeeksuite.credentials,
      tags: credentials }
  - { role: geogeeksuite.storage,
      tags: storage }
  - { role: geogeeksuite.geodatabase,
      tags: pg }
  - { role: geogeeksuite.pgadmin,
      tags: pga }
  - { role: geogeeksuite.startpage,
      tags: startpage }
  - { role: geogeeksuite.webhoster,
      tags: webhoster }
  - { role: geogeeksuite.ingress,
      tags: ingress }
  - { role: geogeeksuite.ubuntu,
      tags: ubuntu }
  - { role: geogeeksuite.notebooks,
      tags: notebooks }
  - { role: geogeeksuite.jupyter,
      tags: jupyter }
  - { role: geogeeksuite.rabbitmq,
      tags: rabbitmq }
  - { role: geogeeksuite.gdal,
      tags: gdal }
  - { role: geogeeksuite.osm2pgsql,
      tags: osm2pgsql }



